version: "2.3"
services:
  base:
    build:
      context: .
  dev:
    extends:
      service: base
    environment:
      - ALPHA_APi_KEY=${ALPHA_APi_KEY}
    ports:
      - "8080:8080"
    networks:
      - dev-network

  artillery:
    image: artillery-wrapper:latest
    entrypoint: ["sh", "/app/bin/run-artillery.sh"]
    environment:
      - APP_URL=http://dev:8080
    volumes:
      - ".:/app"
    networks:
      - dev-network
    links:
      - "dev"



networks:
  dev-network:
    driver: bridge

